kind = "DojoContract"
class_hash = "0x70a6df51e9a8519be571e87f37fd7fe6a11c9d9a0700eedc8163f2b364c98b4"
original_class_hash = "0x70a6df51e9a8519be571e87f37fd7fe6a11c9d9a0700eedc8163f2b364c98b4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-actions-7a1c7102.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-actions"
systems = [
    "spawn",
    "move",
]
manifest_name = "dojo_starter-actions-7a1c7102"
