kind = "DojoModel"
class_hash = "0x7b5d5dab99f884f5b6652351e69d90c46165686d71fff8631201d2ea78d9fd9"
original_class_hash = "0x7b5d5dab99f884f5b6652351e69d90c46165686d71fff8631201d2ea78d9fd9"
abi = "manifests/dev/base/abis/models/dojo_starter-DirectionsAvailable-77844f1f.json"
tag = "dojo_starter-DirectionsAvailable"
qualified_path = "dojo_starter::models::directions_available"
manifest_name = "dojo_starter-DirectionsAvailable-77844f1f"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
