kind = "DojoModel"
class_hash = "0x45303b12635ea9dbf7550bf002f0bb3af64758c993310a9a32e4d59282bde52"
original_class_hash = "0x45303b12635ea9dbf7550bf002f0bb3af64758c993310a9a32e4d59282bde52"
abi = "manifests/dev/base/abis/models/dojo_starter-Moved-504403e5.json"
tag = "dojo_starter-Moved"
qualified_path = "dojo_starter::systems::actions::actions::moved"
manifest_name = "dojo_starter-Moved-504403e5"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
