kind = "DojoModel"
class_hash = "0x2b4424c8d49439f5a6da2577f92ed6a14a6b47365ed90119c7750a72c5c7c91"
original_class_hash = "0x2b4424c8d49439f5a6da2577f92ed6a14a6b47365ed90119c7750a72c5c7c91"
abi = "manifests/dev/base/abis/models/dojo_starter-Moves-2a29373f.json"
tag = "dojo_starter-Moves"
qualified_path = "dojo_starter::models::moves"
manifest_name = "dojo_starter-Moves-2a29373f"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false

[[members]]
name = "can_move"
type = "bool"
key = false
